const QUERY_KEY_USER = "user";
const QUERY_KEY_REPOS = "repos";
const REPOS_PER_PAGE = 4;
const BUTTONS_PER_PAGINATION = 7;

export {
  QUERY_KEY_USER,
  QUERY_KEY_REPOS,
  REPOS_PER_PAGE,
  BUTTONS_PER_PAGINATION,
};
